#ansible-playbook install-dse.yml
- hosts: preprod
  user: root
  become: yes
  become_method: sudo
  vars:
    dse_username: 'quentin.ambard@datastax.com'
    dse_password: 'QuentinAcademy1'
    opscenter:
      interface: 'localhost'
  roles:

  #############################
  #Tune os settings. Apply datastax recommended settings.
  - role: os-tuning
    os:
      #Enable extra tuning conf. Should be carefully used.
      advanced_tuning: True
      #will execute a regexp to detect blocks (all blocks will be tuned as SSD !).
      autodetect_block: True
      #If autodetect_block = False, manually list SSD here.
      ssd_blocks: ["xvda1", "xvdb1", "xvdb2"] #["sda", "sdb"]
      #If you have any HDD disks, set autodetect_block to False and list HDD drive here.
      hdd_blocks: [] #["sda", "sdb"]
