#keyspaces must be filled. search for "keyspace'
instances:
  - host: localhost
    port: 7199
    cassandra_aliasing: false
    name: cassandra
  #   user: username
  #   password: password
  #   process_name_regex: .*process_name.* # Instead of specifying a host, and port. The agent can connect using the attach api.
  #                                        # This requires the JDK to be installed and the path to tools.jar to be set below.
  #   tools_jar_path: /usr/lib/jvm/java-7-openjdk-amd64/lib/tools.jar # To be set when process_name_regex is set
  #   name: cassandra_instance
  #   # java_bin_path: /path/to/java # Optional, should be set if the agent cannot find your java executable
  #   # java_options: "-Xmx200m -Xms50m" # Optional, Java JVM options
  #   # trust_store_path: /path/to/trustStore.jks # Optional, should be set if ssl is enabled
  #   # trust_store_password: password


init_config:
  # List of metrics to be collected by the integration
  # Read http://docs.datadoghq.com/integrations/java/ to learn how to customize it
  conf:
    - include:
        domain: org.apache.cassandra.metrics
        type: ClientRequest
        scope:
          - Read
        name:
          - Latency
        attribute:
          50thPercentile:
            alias: cassandra.read.latency.50thPercentile
          95thPercentile:
            alias: cassandra.read.latency.95thPercentile
          99thPercentile:
            alias: cassandra.read.latency.99thPercentile
          Max:
            alias: cassandra.read.latency.Max
          OneMinuteRate:
            alias: cassandra.read.latency.OneMinuteRate
    - include:
        domain: org.apache.cassandra.metrics
        type: ClientRequest
        scope:
          - Write
        name:
          - Latency
        attribute:
          50thPercentile:
            alias: cassandra.write.latency.50thPercentile
          95thPercentile:
            alias: cassandra.write.latency.95thPercentile
          99thPercentile:
            alias: cassandra.write.latency.99thPercentile
          Max:
            alias: cassandra.write.latency.Max
          OneMinuteRate:
            alias: cassandra.write.latency.OneMinuteRate
    - include:
        domain: org.apache.cassandra.metrics
        type: Storage
        name:
          - TotalHintsInProgress
    - include:
        domain: org.apache.cassandra.metrics
        type: ColumnFamily
        keyspace:
          - XXXXXXXX
          - XXXXXXXX
        name:
          - TotalDiskSpaceUsed
          - LiveDiskSpaceUsed
          - BloomFilterFalseRatio
          - CompressionRatio
          - LiveSSTableCount
          - MaxRowSize
          - MeanRowSize
          - ReadLatency
          - WriteLatency
        attribute:
          - Value
          - Count
          - Mean
          - 99thPercentile
          - Max
    - include:
        domain: org.apache.cassandra.metrics
        type: Cache
        name:
          - Hits
          - Requests
        attribute:
          - Count
    - include:
        domain: org.apache.cassandra.metrics
        type: ThreadPools
        path: request
        name:
          - ActiveTasks
          - PendingTasks
          - CurrentlyBlockedTasks