- name: adding dse repo
  apt_repository: repo='deb http://{{dse_username}}:{{dse_password}}@debian.datastax.com/enterprise stable main' state=present update_cache=yes
  register: dseAptkey

- name: adding dse repo key
  apt_key: url=https://debian.datastax.com/debian/repo_key state=present
  when: dseAptkey.changed

- name: adding datastax community repo
  apt_repository: repo='deb http://debian.datastax.com/community stable main' state=present update_cache=yes
  register: datastaxAptkey

- name: adding datastax community repo key
  apt_key: url=https://debian.datastax.com/debian/repo_key state=present
  when: datastaxAptkey.changed

- name: updating machine
  apt: update_cache=yes
  when: dseAptkey.changed or datastaxAptkey.changed