- name: spark activation in /etc/default/dse
  lineinfile:
    dest: /etc/default/dse
    line: SPARK_ENABLED=1
    state: present
    regexp: SPARK_ENABLED=.

- name: configuring spark default
  template: src={{ role_path }}/templates/spark/spark-defaults.conf dest=/etc/dse/spark/spark-defaults.conf

- name: configuring spark env
  template: src={{ role_path }}/templates/spark/spark-env.sh dest=/etc/dse/spark/spark-env.sh

- name: creating spark-events log folder
  file: path=/opt/spark/data/spark-events owner=cassandra group=cassandra mode=760 state=directory


