- name: installing datastax enterprise
  apt: pkg=dse-full state=installed allow_unauthenticated=yes
  register: dse

- name: configuring datastax enterprise
  template: src={{ role_path }}/templates/cassandra/cassandra.yaml dest=/etc/dse/cassandra/cassandra.yaml

- name: configuring cassandra jvm option
  template: src={{ role_path }}/templates/cassandra/jvm.options dest=/etc/dse/cassandra/jvm.options

- name: set cassandra folder permission
  file: path={{item}} owner=cassandra group=cassandra mode=760 state=directory
  with_items:
    - "{{cassandra.data_file_directories}}"
    - "{{cassandra.hints_directory}}"
    - "{{cassandra.saved_caches_directory}}"
    - "{{cassandra.commitlog_directory}}"

- name: configuring gossiping snitch
  template: src={{ role_path }}/templates/cassandra/cassandra-rackdc.properties dest=/etc/dse/cassandra/cassandra-rackdc.properties
