- name: install epel-release (CentOS)
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: installing some extra dependencies
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - wget
    - curl
    - htop
    - vim
    - sysstat


- name: Fetch Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  ignore_errors: true
  register: installed_java_version

- name: Copy java rpm file to server
  copy:
     src: jdk-8u171-linux-x64.rpm
     dest: /tmp/jdk-8u171-linux-x64.rpm
  when: installed_java_version is failed or installed_java_version.stdout == '' or installed_java_version.stdout is version_compare('1.8', '<')

- name: Install java package.
  yum:
     name: /tmp/jdk-8u171-linux-x64.rpm
     state: present
  when: installed_java_version is failed or installed_java_version.stdout == '' or installed_java_version.stdout is version_compare('1.8', '<')

- name: Clean java rpm
  file:
    state: absent
    path: /tmp/jdk-8u171-linux-x64.rpm
  when: installed_java_version is failed  or installed_java_version.stdout == '' or installed_java_version.stdout is version_compare('1.8', '<')

- name: Make Java available for system
  command: 'alternatives --install "/usr/bin/java" "java" "/usr/java/latest/bin/java" 2000'
  when: installed_java_version is failed  or installed_java_version.stdout == '' or installed_java_version.stdout is version_compare('1.8', '<')
