zookeeper:
  data_dir: "/opt/zookeeper_data"
  clientPort: 2181
  maxClientCnxns: 0
  leaderPort: 2888
  electionPort: 3888
  tickTime: 2000
  initLimit: 10
  syncLimit: 5
  heapmax: 1g 
  heapmin: 1g

kafka_bin_dir: "/opt/kafka"
kafka:
  user:
    shell: /bin/bash
    groupname: kafka
    username: kafka
  log_dir: "/var/log/kafka" #Kafka logs
  log_dirs: "/opt/kafka_log" #Kafka data ddir
  apacheversion: 2.11-1.0.1
  heapmax: 2g
  heapmin: 2g
  port: 9092
  zk_connect: '{% for host in groups["kafkaservers"] %}{{kafka_listen_ip}}:{{zookeeper.clientPort}}{% if not loop.last %},{% endif %}{% endfor %}'
  log_retention_hours: 168
  num_partitions: 9
  num_network_threads: 3
  num_io_threads: 8
  socket_send_buffer_bytes: 102400
  socket_receive_buffer_bytes: 102400
  socket_request_max_bytes: 104857600
  num_recovery_threads_per_data_dir: 1
  offsets_topic_replication_factor: 1
  transaction_state_log_replication_factor: 1
  transaction_state_log_min_isr: 1
  log_segment_bytes: 1073741824
  log_retention_check_interval_ms: 300000
  delete_topic_enable: true
  unclean_leader_election_enable: false
  default_replication_factor: 3
  zookeeper_connection_timeout_ms: 150000
  group_initial_rebalance_delay_ms: 0
  jmx_port: 9096

