- name: Add datastax repository
  yum_repository:
    name: dataStax_enterprise
    description: DataStax Repo for DataStax Enterprise
    baseurl: https://{{dse.repo_username}}:{{dse.repo_password}}@rpm.datastax.com/enterprise
    gpgcheck: no


#- name: copy dse rpm
#  copy:
#    src: /home/quentin/Downloads/dse-full-5.0.5-1.noarch.rpm
#    dest: /tmp/dse-full.noarch.rpm
#
#- name: Install dse full rpm
#  yum:
#    name: /tmp/dse-full.noarch.rpm
#    state: present
#
#- name: copy dse rpm
#  copy:
#    src: /home/quentin/Downloads/datastax-agent-6.0.7-1.noarch.rpm
#    dest: /tmp/datastax-agent.noarch.rpm
#
#
#- name: Install datastax agent rpm
#  yum:
#    name: /tmp/datastax-agent.noarch.rpm
#    state: present